### PR TITLE
Use a base URI set in config for Custos Authnz backend. 

### PR DESCRIPTION
**Pull request by VJalili**

### CODE REVIEW

**Comment by VJalili** [comment]
@machristie 

1- I think we need a rebase, or merge of latest dev;
2- Would it be possible for you to check the unit test?

**Comment by machristie** [comment]
@VJalili I rebased my branch, but I also changed the base branch to `keycloak-integration` instead of dev. That looks like it did the trick of removing all of those other commits.

**Comment by machristie** [comment]
@VJalili I resolved the merge conflicts. I'll take a look at the unit test.

**Comment by VJalili** [comment]
@machristie Sounds great, thanks!

**Pull request merged**
